-- ============================================================
-- UMTCEMS Shared Schema
-- Core structure comes from appdev.drawio.xml.
-- Compatibility columns are kept so the team can finish their
-- assigned modules without fighting the database layer.
-- Target: Supabase PostgreSQL (public schema)
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL REFERENCES roles(role_id),
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    contact_no VARCHAR(50),
    club_name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS clubs (
    club_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    club_rep_user_id BIGINT UNIQUE REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS event_proposals (
    proposal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id BIGINT REFERENCES clubs(club_id),
    submitted_by BIGINT REFERENCES users(user_id),
    title VARCHAR(255) NOT NULL,
    club_name VARCHAR(255),
    submitter_name VARCHAR(255),
    date_submitted VARCHAR(100),
    event_date TEXT,
    venue VARCHAR(255),
    objective TEXT,
    participants VARCHAR(255),
    description TEXT,
    budget TEXT,
    committee TEXT,
    logistics TEXT,
    outcomes TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING_ADVISOR',
    history TEXT,
    created_at VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS proposal_reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL REFERENCES event_proposals(proposal_id) ON DELETE CASCADE,
    reviewer_id BIGINT REFERENCES users(user_id),
    review_role VARCHAR(100) NOT NULL,
    decision VARCHAR(50) NOT NULL,
    comments TEXT,
    review_date VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS post_event_reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL UNIQUE REFERENCES event_proposals(proposal_id) ON DELETE CASCADE,
    submitted_by BIGINT REFERENCES users(user_id),
    submission_date VARCHAR(100),
    report_file VARCHAR(255),
    photos TEXT,
    event_summary TEXT,
    attendance_count INTEGER CHECK (attendance_count IS NULL OR attendance_count >= 0),
    total_expenses TEXT,
    problems_faced TEXT,
    improvements TEXT
);

CREATE TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL REFERENCES event_proposals(proposal_id) ON DELETE CASCADE,
    author_name VARCHAR(255),
    author_role VARCHAR(50),
    content TEXT,
    created_at VARCHAR(100),
    type VARCHAR(100),
    tag VARCHAR(100)
);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS club_name VARCHAR(255);

ALTER TABLE event_proposals
    DROP CONSTRAINT IF EXISTS event_proposals_budget_check;

ALTER TABLE event_proposals
    ALTER COLUMN club_id DROP NOT NULL,
    ALTER COLUMN submitted_by DROP NOT NULL,
    ALTER COLUMN event_date TYPE TEXT USING event_date::text,
    ALTER COLUMN budget TYPE TEXT USING budget::text,
    ALTER COLUMN created_at TYPE VARCHAR(100) USING created_at::text;

ALTER TABLE event_proposals
    ADD COLUMN IF NOT EXISTS club_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS submitter_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS date_submitted VARCHAR(100),
    ADD COLUMN IF NOT EXISTS objective TEXT,
    ADD COLUMN IF NOT EXISTS participants VARCHAR(255),
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS committee TEXT,
    ADD COLUMN IF NOT EXISTS logistics TEXT,
    ADD COLUMN IF NOT EXISTS outcomes TEXT,
    ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'PENDING_ADVISOR',
    ADD COLUMN IF NOT EXISTS history TEXT;

ALTER TABLE proposal_reviews
    ALTER COLUMN reviewer_id DROP NOT NULL,
    ALTER COLUMN review_date TYPE VARCHAR(100) USING review_date::text;

ALTER TABLE post_event_reports
    DROP CONSTRAINT IF EXISTS post_event_reports_total_expenses_check;

ALTER TABLE post_event_reports
    ALTER COLUMN submitted_by DROP NOT NULL,
    ALTER COLUMN submission_date TYPE VARCHAR(100) USING submission_date::text,
    ALTER COLUMN total_expenses TYPE TEXT USING total_expenses::text;

ALTER TABLE post_event_reports
    ADD COLUMN IF NOT EXISTS report_file VARCHAR(255),
    ADD COLUMN IF NOT EXISTS photos TEXT,
    ADD COLUMN IF NOT EXISTS problems_faced TEXT,
    ADD COLUMN IF NOT EXISTS improvements TEXT;

CREATE INDEX IF NOT EXISTS idx_users_role_id
    ON users(role_id);

CREATE INDEX IF NOT EXISTS idx_users_club_name
    ON users(club_name);

CREATE INDEX IF NOT EXISTS idx_event_proposals_club_id
    ON event_proposals(club_id);

CREATE INDEX IF NOT EXISTS idx_event_proposals_submitted_by
    ON event_proposals(submitted_by);

CREATE INDEX IF NOT EXISTS idx_event_proposals_club_name
    ON event_proposals(club_name);

CREATE INDEX IF NOT EXISTS idx_event_proposals_status
    ON event_proposals(status);

CREATE INDEX IF NOT EXISTS idx_proposal_reviews_proposal_id
    ON proposal_reviews(proposal_id);

CREATE INDEX IF NOT EXISTS idx_proposal_reviews_reviewer_id
    ON proposal_reviews(reviewer_id);

CREATE INDEX IF NOT EXISTS idx_post_event_reports_submitted_by
    ON post_event_reports(submitted_by);

CREATE INDEX IF NOT EXISTS idx_comments_proposal_id
    ON comments(proposal_id);

INSERT INTO roles (role_id, role_name, description)
VALUES
    (1, 'CLUB_REP', 'Club Representative'),
    (2, 'ADVISOR', 'Club Advisor'),
    (3, 'MPP_EXCO', 'MPP Club EXCO'),
    (4, 'HEPA_STAFF', 'HEPA Staff')
ON CONFLICT (role_id) DO UPDATE
SET role_name = EXCLUDED.role_name,
    description = EXCLUDED.description;

COMMIT;
