BEGIN;

CREATE TABLE IF NOT EXISTS proposal_documents (
    document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL REFERENCES event_proposals(proposal_id) ON DELETE CASCADE,
    document_name VARCHAR(255) NOT NULL,
    document_url TEXT NOT NULL,
    document_type VARCHAR(100),
    uploaded_at VARCHAR(100)
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'post_event_reports'
          AND column_name = 'photos'
          AND data_type <> 'jsonb'
    ) THEN
        EXECUTE 'ALTER TABLE post_event_reports ALTER COLUMN photos DROP DEFAULT';
        EXECUTE $sql$
            ALTER TABLE post_event_reports
            ALTER COLUMN photos TYPE JSONB
            USING CASE
                WHEN photos IS NULL OR btrim(photos) = '' THEN '[]'::jsonb
                WHEN left(btrim(photos), 1) = '[' THEN photos::jsonb
                ELSE jsonb_build_array(photos)
            END
        $sql$;
    END IF;
END $$;

ALTER TABLE post_event_reports
    ALTER COLUMN photos SET DEFAULT '[]'::jsonb;

UPDATE post_event_reports
SET photos = '[]'::jsonb
WHERE photos IS NULL;

ALTER TABLE post_event_reports
    ALTER COLUMN photos SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_proposal_documents_proposal_id
    ON proposal_documents(proposal_id);

COMMIT;
